// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hckCyxY8wcYsFy9XimTT2R0JTyemVAE',
    appId: '1:695779883104:web:b4e6c690b16ce6f768ab05',
    messagingSenderId: '695779883104',
    projectId: 'foodrushapp',
    authDomain: 'foodrushapp.firebaseapp.com',
    storageBucket: 'foodrushapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAISHMWjata_-wPLMBkYFggiJlokkpQ_cs',
    appId: '1:695779883104:android:6e67f486013079e468ab05',
    messagingSenderId: '695779883104',
    projectId: 'foodrushapp',
    storageBucket: 'foodrushapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAg4V0Gfks2do2wW2iN0f1SnAd2rH785M',
    appId: '1:695779883104:ios:a80dac7ad626ef8a68ab05',
    messagingSenderId: '695779883104',
    projectId: 'foodrushapp',
    storageBucket: 'foodrushapp.firebasestorage.app',
    iosBundleId: 'com.example.foodRush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAg4V0Gfks2do2wW2iN0f1SnAd2rH785M',
    appId: '1:695779883104:ios:a80dac7ad626ef8a68ab05',
    messagingSenderId: '695779883104',
    projectId: 'foodrushapp',
    storageBucket: 'foodrushapp.firebasestorage.app',
    iosBundleId: 'com.example.foodRush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4hckCyxY8wcYsFy9XimTT2R0JTyemVAE',
    appId: '1:695779883104:web:e37baf381b0960c768ab05',
    messagingSenderId: '695779883104',
    projectId: 'foodrushapp',
    authDomain: 'foodrushapp.firebaseapp.com',
    storageBucket: 'foodrushapp.firebasestorage.app',
  );
}
